version: '3'
services:
  web:
    build: ./php-mysqli/
    ports:
    - "12345:80"
    volumes:
    - .:/var/www/html
  db:
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - mydata:/var/lib/mysql
    - ./sql/:/docker-entrypoint-initdb.d
volumes:
  mydata:
